In [1]:
# The evolution of 3 point shot over time. 

from nba_api.stats.endpoints import playercareerstats

In [2]:
career = playercareerstats.PlayerCareerStats(player_id='203999')

In [5]:
df = career.season_totals_regular_season.get_data_frame()

In [6]:
df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335,565,...,0.817,166,545,711,512,85,44,226,222,1456

In [7]:
df.columns

Index(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='str')

In [9]:
from nba_api.stats.endpoints import leaguedashteamstats

stats = leaguedashteamstats.LeagueDashTeamStats(
    season="2024-25",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
)

df = stats.get_data_frames()[0]

df.head()

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,82,40,42,0.488,48.2,43.4,91.8,0.472,...,14,2,26,2,12,15,22,8,5,18
1,1610612738,Boston Celtics,82,61,21,0.744,48.4,41.6,90.0,0.462,...,8,16,2,29,5,1,2,27,8,3
2,1610612751,Brooklyn Nets,82,26,56,0.317,48.2,37.6,86.1,0.437,...,29,24,23,20,26,27,28,14,29,26
3,1610612766,Charlotte Hornets,82,19,63,0.232,48.2,38.3,89.1,0.430,...,9,26,25,26,21,23,16,22,30,27
4,1610612741,Chicago Bulls,82,39,43,0.476,48.2,43.2,92.0,0.470,...,3,5,20,24,18,18,6,30,6,20

In [11]:
from nba_api.stats.endpoints import leaguedashteamstats
import pandas as pd
import time

seasons = [
    f"{year}-{str(year + 1)[-2:]}"
    for year in range(2010, 2025)
]

all_seasons = []

for season in seasons:
    
    print(f"Downloading {season}...")
    
    stats = leaguedashteamstats.LeagueDashTeamStats(
        season=season,
        season_type_all_star="Regular Season",
        per_mode_detailed="PerGame"
    )
    
    df = stats.get_data_frames()[0]
    
    # Keep the variables we need
    df = df[
        [
            "TEAM_NAME",
            "GP",
            "FGA",
            "FG3A",
            "FG3M",
            "FG3_PCT",
            "PTS"
        ]
    ].copy()
    
    # Add season
    df["SEASON"] = season
    
    # Store this season
    all_seasons.append(df)
    
    # Pause briefly between requests
    time.sleep(1)

Downloading 2010-11...
Downloading 2011-12...
Downloading 2012-13...
Downloading 2013-14...
Downloading 2014-15...
Downloading 2015-16...
Downloading 2016-17...
Downloading 2017-18...
Downloading 2018-19...
Downloading 2019-20...
Downloading 2020-21...
Downloading 2021-22...
Downloading 2022-23...
Downloading 2023-24...
Downloading 2024-25...

In [16]:
for season in all_seasons:
    print(season.columns)
    print(season.head())

Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
             TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT   PTS   SEASON
0        Atlanta Hawks  82  78.4  17.4   6.1    0.352  95.0  2010-11
1       Boston Celtics  82  75.8  13.6   5.0    0.365  96.5  2010-11
2    Charlotte Bobcats  82  77.6  14.7   4.8    0.327  93.3  2010-11
3        Chicago Bulls  82  80.3  17.3   6.2    0.361  98.6  2010-11
4  Cleveland Cavaliers  82  81.1  18.2   6.2    0.342  95.5  2010-11
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
             TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT   PTS   SEASON
0        Atlanta Hawks  66  81.0  20.2   7.5    0.370  96.6  2011-12
1       Boston Celtics  66  77.1  15.0   5.5    0.367  91.8  2011-12
2    Charlotte Bobcats  66  80.2  13.5   4.0    0.295  87.0  2011-12
3        Chicago Bulls  66  82.8  16.9   6.3    0.375  96.3  2011-12
4  Cleveland Cavaliers  66  81.2  19.3   6.7    0.346  93.0  2011-12
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT   PTS   SEASON
0      Atlanta Hawks  82  81.0  23.2   8.6    0.371  98.0  2012-13
1     Boston Celtics  81  79.7  17.2   6.1    0.358  96.5  2012-13
2      Brooklyn Nets  82  79.8  21.5   7.7    0.357  96.9  2012-13
3  Charlotte Bobcats  82  81.1  17.1   5.7    0.335  93.4  2012-13
4      Chicago Bulls  82  81.7  15.4   5.4    0.353  93.2  2012-13
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  81.6  25.8   9.4    0.363  101.0  2013-14
1     Boston Celtics  82  83.9  21.1   7.0    0.333   96.2  2013-14
2      Brooklyn Nets  82  77.9  23.4   8.6    0.369   98.5  2013-14
3  Charlotte Bobcats  82  82.1  17.9   6.3    0.351   96.9  2013-14
4      Chicago Bulls  82  80.2  17.8   6.2    0.348   93.7  2013-14
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  81.7  26.2  10.0    0.380  102.5  2014-15
1     Boston Celtics  82  87.9  24.6   8.0    0.327  101.4  2014-15
2      Brooklyn Nets  82  83.0  19.9   6.6    0.331   98.0  2014-15
3  Charlotte Hornets  82  84.5  19.1   6.1    0.318   94.2  2014-15
4      Chicago Bulls  82  82.9  22.3   7.9    0.353  100.8  2014-15
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  84.4  28.4   9.9    0.350  102.8  2015-16
1     Boston Celtics  82  89.2  26.1   8.7    0.335  105.7  2015-16
2      Brooklyn Nets  82  84.4  18.4   6.5    0.352   98.6  2015-16
3  Charlotte Hornets  82  84.4  29.4  10.6    0.362  103.4  2015-16
4      Chicago Bulls  82  87.4  21.4   7.9    0.371  101.6  2015-16
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  84.4  26.1   8.9    0.341  103.2  2016-17
1     Boston Celtics  82  85.1  33.4  12.0    0.359  108.0  2016-17
2      Brooklyn Nets  82  85.2  31.6  10.7    0.338  105.8  2016-17
3  Charlotte Hornets  82  85.4  28.6  10.0    0.351  104.9  2016-17
4      Chicago Bulls  82  87.1  22.3   7.6    0.340  102.9  2016-17
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  85.5  31.0  11.2    0.360  103.4  2017-18
1     Boston Celtics  82  85.1  30.4  11.5    0.377  104.0  2017-18
2      Brooklyn Nets  82  86.8  35.7  12.7    0.356  106.6  2017-18
3  Charlotte Hornets  82  86.7  27.2  10.0    0.369  108.2  2017-18
4      Chicago Bulls  82  88.8  31.1  11.0    0.355  102.9  2017-18
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  91.8  37.0  13.0    0.352  113.3  2018-19
1     Boston Celtics  82  90.5  34.5  12.6    0.365  112.4  2018-19
2      Brooklyn Nets  82  89.7  36.2  12.8    0.353  112.2  2018-19
3  Charlotte Hornets  82  89.8  33.9  11.9    0.351  110.7  2018-19
4      Chicago Bulls  82  87.9  25.9   9.1    0.351  104.9  2018-19
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  67  90.6  36.1  12.0    0.333  111.8  2019-20
1     Boston Celtics  72  89.6  34.5  12.6    0.364  113.7  2019-20
2      Brooklyn Nets  72  90.3  38.1  13.1    0.343  111.8  2019-20
3  Charlotte Hornets  65  85.9  34.3  12.1    0.352  102.9  2019-20
4      Chicago Bulls  65  88.6  35.1  12.2    0.348  106.8  2019-20
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  72  87.2  33.4  12.4    0.373  113.7  2020-21
1     Boston Celtics  72  88.9  36.4  13.6    0.374  112.6  2020-21
2      Brooklyn Nets  72  87.3  36.1  14.2    0.392  118.6  2020-21
3  Charlotte Hornets  72  87.8  37.0  13.7    0.369  109.5  2020-21
4      Chicago Bulls  72  88.6  34.0  12.6    0.370  110.7  2020-21
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  88.3  34.4  12.9    0.374  113.9  2021-22
1     Boston Celtics  82  87.4  37.1  13.2    0.356  111.8  2021-22
2      Brooklyn Nets  82  88.4  31.7  11.5    0.361  112.9  2021-22
3  Charlotte Hornets  82  91.4  38.2  13.9    0.365  115.3  2021-22
4      Chicago Bulls  82  86.9  28.8  10.6    0.369  111.6  2021-22
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  92.4  30.5  10.8    0.352  118.4  2022-23
1     Boston Celtics  82  88.8  42.6  16.0    0.377  117.9  2022-23
2      Brooklyn Nets  82  85.1  33.8  12.8    0.378  113.4  2022-23
3  Charlotte Hornets  82  90.4  32.5  10.7    0.330  111.0  2022-23
4      Chicago Bulls  82  86.8  28.9  10.4    0.361  113.1  2022-23
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  92.5  37.7  13.7    0.364  118.3  2023-24
1     Boston Celtics  82  90.2  42.5  16.5    0.388  120.6  2023-24
2      Brooklyn Nets  82  89.1  36.7  13.3    0.362  110.4  2023-24
3  Charlotte Hornets  82  87.0  34.0  12.1    0.355  106.6  2023-24
4      Chicago Bulls  82  89.5  32.1  11.5    0.358  112.3  2023-24
Index(['TEAM_NAME', 'GP', 'FGA', 'FG3A', 'FG3M', 'FG3_PCT', 'PTS', 'SEASON'], dtype='str')
           TEAM_NAME  GP   FGA  FG3A  FG3M  FG3_PCT    PTS   SEASON
0      Atlanta Hawks  82  91.8  37.7  13.5    0.358  118.2  2024-25
1     Boston Celtics  82  90.0  48.2  17.8    0.368  116.3  2024-25
2      Brooklyn Nets  82  86.1  39.4  13.6    0.344  105.1  2024-25
3  Charlotte Hornets  82  89.1  38.3  13.0    0.339  105.1  2024-25
4      Chicago Bulls  82  92.0  42.0  15.4    0.367  117.8  2024-25